Feature/remove governance dependency
SumeroApp/sumero-contracts pull request #88
Opened 2023-03-03 13:27 UTC by RojhatToptamus

2023-03-03 14:04 UTC, ShubhamChndrvnshi reviewed
Looks good

2023-03-06 09:49 UTC, KohliSuraj requested changes

2023-03-06 09:49 UTC, KohliSuraj commented on contracts/UMA/financial-templates/expiring-multiparty/PricelessPositionManager.sol
> +        Testable(address(0))
@RojhatToptamus I think since we are now touching this part of code, let's remove Testable contract all together. We are not using it anyways.

2023-03-06 09:49 UTC, KohliSuraj commented on contracts/UMA/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol
> +        //Sumero FIX
Can we remove sumero fix comments from the code?

2023-03-06 09:49 UTC, KohliSuraj commented on contracts/UMA/financial-templates/expiring-multiparty/PricelessPositionManager.sol
> +        require(msg.sender == owner);
👍

2023-03-13 08:22 UTC, KohliSuraj requested changes
@RojhatToptamus we can delete Timer.sol and Testable.sol from our repo now.

We can also delete `006_deploy_uma_timer.js` and rename the deployment scripts.

2023-03-13 08:22 UTC, KohliSuraj commented on contracts/UMA/financial-templates/expiring-multiparty/PricelessPositionManager.sol
> -        return
we can remove this `_getFinancialContractsAdminAddress`  internal function, since it's not being used anymore.

2023-03-13 13:31 UTC, KohliSuraj approved these changes

2023-03-20 08:56 UTC, merged