feature/airdrop contract & scripts
SumeroApp/sumero-contracts pull request #90
Opened 2023-03-07 12:18 UTC by RojhatToptamus

2023-03-22 18:06 UTC, KohliSuraj requested changes

2023-03-22 18:06 UTC, KohliSuraj commented on contracts/ClayDistributor.sol
> +import {IERC20, SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
Can we import contracts like this in solidity? I can't seem to find this syntax in Solidity official docs.

https://docs.soliditylang.org/en/v0.8.19/path-resolution.html

2023-03-22 18:06 UTC, KohliSuraj commented on contracts/ClayDistributor.sol
Code looks good 👍

2023-03-22 18:06 UTC, KohliSuraj commented on tasks/build-merkle.js
> +            const workbook = XLSX.readFile('../utils/airdrop.xlsx');
We should add an optional parameter and allow the user to either hardcode the addresses in an array or input a file path.

We can add a function which just returns the addresses, and this hardhat task will hash it and create the merkle tree.

2023-03-22 18:06 UTC, KohliSuraj commented on tasks/build-merkle.js
> +            let start = 5;
It's not clear why these variables are hardcoded. e.g. start = 5, end = 1503 etc..

It seems even a tiny change in the excel will break this code. Probably, that's okay, since we can control which file we give to this task.

2023-03-22 18:06 UTC, KohliSuraj commented on tasks/build-merkle.js
> +            const leaf = KECCAK256('0x356E25e6bF2D5f68684F5b758f644fbF02f6a782');
This works, but when I give a valid leaf, the verify function still fails. @RojhatToptamus Let's do a pairing session tomorrow to test this? Probably I'm missing something.

2023-03-22 18:06 UTC, KohliSuraj commented on tasks/clay-claim.js
> +            for (const address in addressList) {
We can reuse a lot of code between this file and build-merkle task file.

2023-03-22 18:06 UTC, KohliSuraj commented on test/005_clay_distributor_test.js
@RojhatToptamus This test file is excellent. It works as expected 🚀 💯 

Even though, I'm not able to run build merkle task properly, after going through this test file and running it, I'm confident code is working fine 👍

2023-03-23 07:52 UTC, RojhatToptamus commented on tasks/clay-claim.js
> +            for (const address in addressList) {
Yes, they are pretty similar.

2023-03-23 07:53 UTC, RojhatToptamus commented on tasks/build-merkle.js
> +            let start = 5;
In the Excel file, addresses start on row 5 and end on row 1503. But of course, we can adjust the code to start from 0.

2023-03-23 08:38 UTC, KohliSuraj commented on contracts/ClayDistributor.sol
> +import {IERC20, SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
Reverting to normal imports

2023-03-23 08:42 UTC, KohliSuraj commented on tasks/build-merkle.js
> +            const leaf = KECCAK256('0x356E25e6bF2D5f68684F5b758f644fbF02f6a782');
I had a typo, and was using proof from another leaf. It's working now.

2023-03-23 08:45 UTC, KohliSuraj approved these changes

2023-03-23 08:50 UTC, merged